### PR TITLE
Refactor Delegates and SettingsScreen

### PR DESCRIPTION
**Pull request by nullableVoidPtr**

### CODE REVIEW

**Comment by BonusPlay** [comment]
Question, why do we even need a `std::map` in `Delegate` class? Shouldn't we just hold a `std::vector` of handles? What's the goal of `std::string tag`?

Shouldn't a delegate be an object that you can subscribe to (with a function) and when it's called, it should call all callbacks that subscribed to it?

**Comment by nullableVoidPtr** [comment]
I used it as a replacement to the `UnionCast` and `void *`, as the `Delegate` also needs the ability to remove functions (particularly members of a class, which could be removed using `RemoveAll(objPtr)`). I think using `tag`s isn't that much different to how the previous solution handled lambdas. We could revert back to the previous solution.

**Comment by BonusPlay** [comment]
Looking at C#'s Delegate class (pretty much same as ours) it doesn't have any tag. When you subscribe, you pass a `function` to it. When you want to unsubscribe, you just pass the same function that you want to unsubscribe. This does have a disadvantage (or advantage?) - if the handler function is private, you can't unsubscribe it from outside of the class. To do that you need notify the class that it should unsubscribe. Isn't that a better way?

**Comment by nullableVoidPtr** [comment]
I did feel as if it's potentially unsafe, what with the rampant casting to `void *` among other things. I had the idea for tags [here](https://nikitablack.github.io/2016/04/12/Generic-C-delegates.html), but I think I could possibly do something with comparison operators in `FunctionBinding` and its derived classes.

**Comment by nullableVoidPtr** [comment]
In order to compare two function pointers, you can't use `std::function`. But using raw function pointers means binding lambdas, even with the correct signature (`[](A...) -> R {}`) is impossible.

I feel as if using lambdas for something like `Delegate` would be bad practice anyways; seems like a code smell to me...

**Comment by BonusPlay** [comment]
I'd never expect that you can't compare `std::function`. In that case you are right, tags are proper way to go. However, I believe that allowing a handler function to be a lambda is very good (in some places this will result in cleaner code). Ofc, that doesn't mean that every delegate handling function should.

**Review by BonusPlay — APPROVED** [review]

**Comment by BonusPlay** [comment]
[Refactor Delegate class](https://trello.com/c/YlekQ8Uh/18-refactor-delegate-class)

**Pull request merged**
