### PR TITLE
Refactor Bindables and update to C++17 for MSVC

### PR DESCRIPTION
**Pull request by nullableVoidPtr**

### CODE REVIEW

**Comment by BonusPlay** [comment]
Thanks for the help. What do you think - is there even a point to having `Delegate` and `Action`, or should we just remove them and have `std::function`s in code?

**Comment by nullableVoidPtr** [comment]
`Delegate` is definitely important - calls multiple Functions, some with an object bound to it, on `OnClick`, `OnChanged`, etc. events - but I don't think `Action` is. I'm planning to refactor `Delegate` to use smart pointers.

**Comment by BonusPlay** [comment]
So, you want me to merge it now, or should I wait till `Action` refactor?

**Comment by nullableVoidPtr** [comment]
Preferrably now, since my refactor to `Delegate` wouldn't change its API, I think.

**Review by BonusPlay — APPROVED** [review]

**Pull request merged**
